### ISSUE TITLE
Industrial power plant should use ProductionCostMultiplier

### ISSUE THREAD

**Issue by Mailaender** [cookgreen/Yuris-Revenge#104]
https://docs.openra.net/en/latest/playtest/traits/#productioncostmultiplier It currently does nothing.

**Comment by cookgreen** [comment]
Seems like I need to attach this trait into the production actor like barracks, war factory and submarine pen but only enabled by Industrial plant

**Comment by cookgreen** [comment]
Another thing is that I hope you guys can provide something which can use some ways to access the traits list of specific openra release or play test version, I am making a Trait Browser in OpenRAModEditor, I hope I can use this thing to fetch all traits rather than I added all traits manually.
Data Format has better is JSON, so that can be parsed easily.

**Comment by cookgreen** [comment]
By the way, the voxel browser can't work in `playtest-20200303` because you guys make some function related to the Rendering Voxel private. I hope you guys can re-consider this decision, or can provide some alternative solution to make voxel browser can work in `playtest-20200303`
I tried to ask the @pchote in discord, but don't get any response.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/pull/17803 for my take on a voxel browser. The `ModelWidget` introduced there is probably what you need as well.

**Comment by Mailaender** [comment]
Regarding your other offtopic post about JSON output you will have to write your own utility command for that. Take https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/UtilityCommands/ExtractTraitDocsCommand.cs as a reference and modify it towards JSON.

**Comment by cookgreen** [comment]
> Regarding your other offtopic post about JSON output you will have to write your own utility command for that. Take https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/UtilityCommands/ExtractTraitDocsCommand.cs as a reference and modify it towards JSON.

I don't think I can run Utility command in the ModEditor

**Comment by cookgreen** [comment]
BTW, after I finished modifying the cs code and update toolchain, can I use the semi-auto update tool to update the yaml file like chrome.yaml, no need to modify one by one?

**Comment by Mailaender** [comment]
> I don't think I can run Utility command in the ModEditor which is a independent winform application not a OpenRA mod.

You will have to run that inside the OpenRA engine project to generate the JSON file or build a ModEditor that can understand the game rules also inside the OpenRA engine project.

**Comment by cookgreen** [comment]
@Mailaender I think I can use Reflection to get all traits inside the OpenRA.Game.exe, just like the UtlityCommand you show to me.
