### ISSUE TITLE
Game save issues:Out of sync in frame 5871

### ISSUE THREAD

**Issue by zgrsgr** [cookgreen/Yuris-Revenge#109]
The file cannot be read directly in the menu interface; when reading the archive, there is a chance that an error will occur, causing the archive to be inaccessible, and the archive to crash.

**Comment by cookgreen** [comment]
@OpenRA

**Comment by cookgreen** [comment]
@OpenRA

**Comment by abcdefg30** [comment]
This is usually caused by one of two things:
- Version mismatches
- Errors in mod code (e.g. wrong usage of `SharedRandom`/`LocalRandom`).

We're not aware of any desyncs in our latest playtest version, so updating to that might help (unlikely however, unless this was caused by minelayers). There's not much we can do without more information here.
