### ISSUE TITLE
Yuri Disc will shutdown the enemy power

### ISSUE THREAD

**Issue by cookgreen** [cookgreen/Yuris-Revenge#34]

**Comment by GraionDilach** [comment]
This feature requires no additional code and is doable within default OpenRA.

**Comment by cookgreen** [comment]
@GraionDilach I think there may be needed a new trait

**Comment by MustaphaTR** [comment]
You don't need a new trait, this can be easily done with a GrantExternalConditionWarhead.

**Comment by GraionDilach** [comment]
What @MustaphaTR said.

**Comment by GraionDilach** [comment]
Incase you're wondering, the trickiest is the refinery drain - but even that one should be doable via a conditional `CashTrickler` upon the refineries enabled by an explicit-for-refineries disk's drain weapon with `GrantExternalConditionWarhead`, which can also enable a positive `CashTrickler` upon the Disk itself with `GrantConditionOnAttack`.

**Comment by cookgreen** [comment]
@GraionDilach Your solution has a problem that if I attack a powerplant, it will also active Disk's `CashTrickler` trait, because `GrantConditionOnAttack` trait will grant condition when Disk attack anything

**Comment by cookgreen** [comment]
@GraionDilach `GrantConditionOnAttack` lack of a target type checking

**Comment by cookgreen** [comment]
@GraionDilach Shutdown power will also has problem, as @MustaphaTR said in Discord, 

> You can use GrantExternalConditionWarhead to grant a condition to the Power Plant, which enables a ProvidesPrerequisites: trait, a GrantConditionOnPrerequisite trait on the Power Plants grant another condition, which disable the Power: traits on the Power Plant.

It is too complicated, if can have a new trait called `ShutdownPower`, it will be more eaiser.

**Comment by GraionDilach** [comment]
>`GrantConditionOnAttack` lack of a target type checking

I said _refineries should have their own weapon which will be used against_. DiskDrain vs DiskDrainRefinery. This allows to use armament name filtering.

If you want a new trait here, that should be `GrantConditionWhenCashflow` or something along to disable refinery targeting when the player has no money. Nothing else required.

> It is too complicated, if can have a new trait called ShutdownPower, it will be more eaiser.

There's no unmanageable complication there. The hack presented as a solution however stinks. The current `InfiltrateForPowerOutage` trait is legacy code which shouldn't be followed but should be superseded by a similar solution based on https://github.com/OpenRA/OpenRA/pull/15281 anyway.

**Comment by cookgreen** [comment]
@GraionDilach If refineries have their own weapon, then the feature will not be original(Because original YR only have one `DiskDrain` weapon, not two )

**Comment by GraionDilach** [comment]
There's no difference at the resulting gameplay between your horrible, harder-to-maintain hack and my OpenRA-adjusted proposal.

Your point would only matter if there would be an accurate INI2YAML converter which would cover the entire INI without any manual tweaks thenafter or the engine would be able to handle the original INI files - but at this point I just hope we both know neither is doable nor either worth the effort necessary.

If OpenRA provides the toolset to deliver accurate ingame experience - no matter the underlying YAML setup - then this fact should be endorsed and this toolkit should be deployed fully to show OpenRA's true potential. There's no point in bothering with hacks for, say, `IsChargeTurret`, when `GrantConditionOnAttack` stacking can do it more cleaner and more flexible than WW could ever dream of.

Of course, there's the other option - sacrificing the flexibility of OpenRA's for a "fake" accuracy - but that delivers a wrong message that everything needs horrible hacks to be done. It implies OpenRA is a dumber engine than it actually is, it implies that the project leader is unable to utilize OpenRA's toolset properly and if taken really seriously, it leads into arbitrary limitations caused by the underlying nature differences of the two engine.

You can't implement the TechnoTypes classing of YR into OpenRA, and if you try to, you just cut your own options with doing so.

However if you intend to maintain a bad codebase, I can intend to stop bothering with and being associated with this project. I maintain a view that code quality should come first and OpenRA's flexible mindset should not be sacrificed for WW accuracy - especially since I know YR itself was a lousy codebase and OpenRA is better than it.

**Comment by cookgreen** [comment]
@GraionDilach 
Nearly morbid pursuit of code quality is a big strike to the game's achievability. Since OpenRA provides the possibility of third-party code to expan OpenRA's features, so you guys should not limit third-party developers to use this feature, and should support. Deliberately emphasize the use of `OpenRA tools`, but all custom codes were classified as `horrible hack`. IT IS UNFAIR!

**Comment by GraionDilach** [comment]
There is a major difference between custom code which duplicates already-existing functionality with limits hardwired into it and custom code which just tries to add new modules to the OpenRA's  modularization infrastructure. I did not say all custom codes are bad - I just say that most of your traits you used to fix this bug are bad. If that would be my point, there would have never been an `OpenRA.Mods.AS` to begin with.

If you extend OpenRA codebase, you should try aiming for extending it with the OpenRA coding mindset and only start deploying external designs when it fails.

The Boris-airstrike (Marker* traits) is a good case where I acknowledge the custom code was necessary, because it improved the modularity on the forcecore-framework. The Robot Control Center-related traits are unneeded though, since RCC providing a prerequisite disabled by `GrantConditionOnPowerState` and this prerequisite disabling Robot Tanks achieves the same result (You can still combine this with `GrantConditionOnTerrain` enabled on water to sink disabled Robot Tanks).

If a generic solution resolves the issue then the additional tailoring is redundant and an effective codebase shouldn't offer redundancies. If I've got the AS `DetonateWeaponPower` which can do Iron Curtain, Genetic Mutator and the Psychic Dominator, then why should I bother to write a custom trait for any of the three? It is still a custom code but it covers three usecases because it's _generic_ enough to cover more usecases.

At RA2 and YR, there should be the forethought that OpenRA eventually might try to merge these somehow into upstream after TS is done. If the YR codebase runs upon an incompatible-with-upstream mindset, then you'll force upstream to reinvent your wheels at that point, which will be just waste on both sides longterm.
